import {summarizeChecks} from './core.js';
import {buildResetCalendar,calendarCoverage,monthAt,moveMonth} from './calendar.js';
const $=id=>document.getElementById(id);
const send=(type,extra={})=>chrome.runtime.sendMessage({type,...extra});
const when=t=>t?new Date(t).toLocaleString('zh-CN',{hour12:false}):'尚未成功';
const extensionVersion=chrome.runtime.getManifest().version;
let lastSignature='';
let calendarCursor=monthAt();
const percent=value=>value===null?'暂无':`${Math.round(value*100)}%`;
const duration=ms=>ms===null?'暂无':ms<60_000?`${Math.round(ms/1000)} 秒`:ms<3_600_000?`${Math.round(ms/60_000)} 分钟`:`${(ms/3_600_000).toFixed(1)} 小时`;
function resetDate(value){if(!value)return '尚未检测到';const parts=Object.fromEntries(new Intl.DateTimeFormat('en',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(value)).map(p=>[p.type,p.value]));return `${parts.year}${parts.month}${parts.day}`;}
function setStatusTone(tone){const card=$('statusCard'),dot=$('statusDot');if(card)card.dataset.tone=tone;if(dot)dot.dataset.tone=tone;}
function renderLastReset(entry){const el=$('lastReset');if(!el)return;el.replaceChildren();const label=document.createElement('strong');label.textContent=`上次 RESET：${resetDate(entry?.publishedAt)}`;el.append(label);if(entry?.url&&/^https:\/\/x\.com\/thsottiaux\/status\/\d+$/.test(entry.url)){const link=document.createElement('a');link.href=entry.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=' · 查看原文 ↗';el.append(link);}}
function card(p,ack=false){const box=document.createElement('article');box.className='card';const title=document.createElement('strong');title.textContent=`${p.test?'【测试】':''}${p.label||p.match?.label||'历史相关消息'}`;box.append(title);if(p.kind==='reset'){const levels={critical:'强提醒',medium:'单次通知',low:'仅面板'},level=p.severity||'critical';const badge=document.createElement('small');badge.className=`severity severity-${level}`;badge.textContent=levels[level];box.append(badge);}const txt=document.createElement('p');txt.textContent=p.text;box.append(txt);const meta=document.createElement('small');meta.textContent=`${when(p.publishedAt||p.createdAt)}${p.source?` · ${p.source==='replies'?'回复':'帖子'}`:''}${p.reason?' · '+p.reason:''}${p.acknowledgedAt?' · 已确认':''}`;box.append(meta);if(p.context){const c=document.createElement('small');c.textContent='可见上下文：'+p.context;box.append(c);}if(p.url&&/^https:\/\/x\.com\/thsottiaux\/status\/\d+$/.test(p.url)){const a=document.createElement('a');a.href=p.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='查看 X 原文 ↗';box.append(a);}if(ack){const b=document.createElement('button');b.textContent='已知晓';b.onclick=()=>act('ack',{key:p.key});box.append(b);}if(p.kind==='reset'&&!p.test&&p.url){const b=document.createElement('button');b.textContent='这不是 RESET';b.title='记录误报并停止这条提醒';b.onclick=async()=>{const r=await act('feedback',{kind:'false_positive',key:p.key},b);if(r?.ok)$('message').textContent='已记录，并停止这条提醒。';};box.append(b);}return box;}
function list(id,items,ack,empty){const el=$(id);if(!el)return;el.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='empty';p.textContent=empty;el.append(p);}else items.forEach(p=>el.append(card(p,ack)));}
function renderSources(sources={}){
  const el=$('sources');if(!el)return;el.replaceChildren();
  const errorLabels={LOGIN_REQUIRED:'需要登录',RATE_LIMITED:'请求受限',NETWORK_BLOCKED:'页面加载失败',DOM_CHANGED:'页面结构变化',EMPTY_TIMELINE:'没有可验证内容',SCAN_TIMEOUT:'读取超时',PAGE_MOVED:'监控页位置错误',UNKNOWN:'未知错误'};
  for(const [key,label] of [['posts','帖子'],['replies','回复']]){
    const source=sources[key]||{},now=Date.now(),backing=source.backoffUntil&&source.backoffUntil>now;
    const box=document.createElement('article');box.className=`source-card ${backing||source.error?'bad':source.lastSuccess?'good':'wait'}`;
    const title=document.createElement('strong');title.textContent=`${label} · ${backing?'退避中':source.error?'异常':source.lastSuccess?'正常':'等待首次读取'}`;box.append(title);
    const detail=document.createElement('small');detail.textContent=backing?`剩余 ${duration(source.backoffUntil-now)} · ${when(source.backoffUntil)} 后重试`:`最近成功：${when(source.lastSuccess)}${source.lastSuccess?` · ${source.lastCount||0} 条`:''}`;box.append(detail);
    if(source.errorCode){const code=document.createElement('small');code.className='error-code';code.textContent=`${errorLabels[source.errorCode]||'读取异常'} · ${source.errorCode}`;box.append(code);}if(source.error){const error=document.createElement('small');error.textContent=source.error;box.append(error);}
    const action=document.createElement('button');action.textContent=source.errorCode==='LOGIN_REQUIRED'?'打开页面登录':backing?'查看来源页':'打开来源页';action.onclick=()=>act('source',{key},action);box.append(action);
    el.append(box);
  }
}
function renderMetrics(state){const el=$('metrics24h');if(!el)return;el.replaceChildren();const m=summarizeChecks(state.checkStats||state.checkLog,Date.now()),cards=[['完整覆盖率',percent(m.fullCoverageRate)],['帖子成功率',percent(m.sourceRates.posts.rate)],['回复成功率',percent(m.sourceRates.replies.rate)],['P95 读取耗时',duration(m.p95DurationMs)],['最长完整覆盖盲区',duration(m.longestBlindMs)],['最近完整覆盖',m.lastFullCoverage?when(m.lastFullCoverage):'尚无']];for(const [label,value] of cards){const box=document.createElement('div');box.className='metric';const strong=document.createElement('strong');strong.textContent=value;const small=document.createElement('small');small.textContent=label;box.append(strong,small);el.append(box);}}
function renderCalendar(state){
  const el=$('resetCalendar');if(!el)return;const view=buildResetCalendar(state,calendarCursor,Date.now()),coverage=calendarCoverage(state,calendarCursor);el.replaceChildren();
  $('calendarMonth').textContent=`${view.month} 月`;$('calendarYear').textContent=view.year;const counts=`确认 ${view.confirmed} 次${view.planned?` · 预告 ${view.planned} 条`:''}`;$('calendarSummary').textContent=coverage.complete?`本月${counts} · 已回填到月初`:coverage.started?`本机记录：${counts} · 回填中${coverage.earliest?`，最早 ${resetDate(coverage.earliest)}`:''}；点“立即检查”可继续`:`本机记录：${counts} · 等待历史回填；点“立即检查”开始`;
  for(const cell of view.cells){if(!cell){const gap=document.createElement('span');gap.className='calendar-gap';el.append(gap);continue;}
    const target=cell.events.find(event=>event.url)?.url?document.createElement('a'):document.createElement('div');target.className=`calendar-day${cell.isToday?' today':''}${cell.isLatest?' latest':''}`;
    if(target.tagName==='A'){target.href=cell.events.find(event=>event.url).url;target.target='_blank';target.rel='noopener noreferrer';}
    const number=document.createElement('span');number.className='day-number';number.textContent=cell.day;target.append(number);
    const marks=document.createElement('span');marks.className='day-marks';for(const event of cell.events){const mark=document.createElement('i');mark.className=`mark ${event.type}`;mark.textContent=event.type==='planned'?'预告':event.type==='banked'?'存':'↻';marks.append(mark);}target.append(marks);
    if(cell.events.length)target.title=cell.events.map(event=>`${event.type==='planned'?'预告':event.type==='banked'?'存入型重置':'确认重置'}：${event.text||event.label||''}`).join('\n');el.append(target);
  }
}
function renderLog(items=[]){
  const el=$('checklog');if(!el)return;el.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='empty';p.textContent='完成第一次检查后显示';el.append(p);return;}
  const triggers={manual:'手动',alarm:'定时',install:'安装',startup:'启动',resume:'恢复'},outcomes={success:'全部正常',partial:'部分成功',failed:'失败',backoff:'退避跳过'};
  items.slice(0,100).forEach(item=>{const row=document.createElement('div');row.className=`check-row ${item.outcome}`;const title=document.createElement('strong');title.textContent=`${when(item.finishedAt)} · ${triggers[item.trigger]||item.trigger} · ${outcomes[item.outcome]||item.outcome}${item.alerts?` · 命中 ${item.alerts} 条`:''}`;row.append(title);const source=document.createElement('small');source.textContent=['posts','replies'].map(key=>{const x=item.sources?.[key];if(!x)return `${key==='posts'?'帖子':'回复'}：无记录`;const status={success:'正常',failed:'异常',backoff:'退避'}[x.status]||x.status;return `${key==='posts'?'帖子':'回复'}：${status}${x.status==='success'?` ${x.count} 条/${x.durationMs}ms`:x.errorCode?` [${x.errorCode}]`:x.error?`（${x.error}）`:''}`;}).join('；');row.append(source);const trace=document.createElement('small');trace.textContent=`检查编号：${item.runId||item.id} · 版本 ${item.appVersion||'旧记录'} · 解析器 ${item.parserVersion||'旧记录'}`;row.append(trace);el.append(row);});
}
async function refresh(){
  try{
    const {state:s,error}=await send('state');if(!s)throw new Error(error||'后台无响应');const stale=s.health.lastSuccess&&Date.now()-s.health.lastSuccess>300_000;const partial=Object.values(s.sources||{}).some(x=>x.error||(x.backoffUntil&&x.backoffUntil>Date.now()));
    const tone=s.paused?'paused':s.health.failures||stale?'danger':s.checkingSince?'working':s.initialized?(partial?'warning':'good'):'waiting';setStatusTone(tone);
    $('status').textContent=s.paused?'监控已暂停':s.health.failures?'监控暂时不可用':stale?'监控状态需要检查':s.checkingSince?'正在检查…':s.initialized?(partial?'监控运行中，部分来源异常':'监控运行正常'):'等待首次检查';
    if($('healthSummary'))$('healthSummary').textContent=s.paused?'不会自动检查或发送提醒。':s.health.failures?'请打开监控页面，确认 X 可以正常访问。':stale?'长时间没有完成检查，请打开监控页面。':s.checkingSince?'正在读取 Tibo 的帖子和回复。':s.initialized?(partial?'可用来源仍会继续监控；你可以在高级诊断中查看原因。':'帖子和回复均在正常检查。'):'点击“立即检查”开始。';
    $('last').textContent=`上次成功检查：${when(s.health.lastSuccess)}`;renderLastReset(s.lastReset);$('coverage').textContent=s.health.failures?(s.health.error||''):'';
    const errors=[s.delivery.notification&&'桌面通知：'+s.delivery.notification,s.delivery.audio&&'提示音：'+s.delivery.audio,s.delivery.window&&'提醒窗口：'+s.delivery.window].filter(Boolean);$('delivery').textContent=errors.join('\n');$('metrics').textContent=`版本 ${extensionVersion} · 成功 ${s.metrics.successes} / 检查 ${s.metrics.attempts} 次 · 待确认 ${s.pending.length} 条`;
    $('paused').checked=s.paused;$('muted').checked=s.muted;renderCalendar(s);renderSources(s.sources);renderMetrics(s);const signature=JSON.stringify([s.pending,s.history,s.recent,s.checkLog,s.feedback]);if(signature!==lastSignature){list('pending',s.pending,true,'目前没有需要你确认的提醒');list('history',[...s.history,...s.recent],false,'首次成功读取后显示');renderLog(s.checkLog);lastSignature=signature;}$('ackall').disabled=!s.pending.length;
  }catch(e){$('message').textContent='无法读取插件状态：'+e.message;}
}
async function act(type,extra={},button){if(button)button.disabled=true;$('message').textContent='';try{const r=await send(type,extra);if(!r?.ok&&!r?.paused)throw new Error(r?.error||'操作失败');await refresh();return r;}catch(e){$('message').textContent=e.message;return null;}finally{if(button)button.disabled=false;}}
async function exportDiagnostics(){const button=$('exportDiagnostics');if(button)button.disabled=true;$('message').textContent='';try{const r=await send('diagnostics');if(!r?.ok)throw new Error(r?.error||'无法生成诊断');const blob=new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Tibo-RESET-诊断-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('message').textContent='诊断文件已导出。';}catch(e){$('message').textContent=e.message;}finally{if(button)button.disabled=false;}}
async function exportBackup(){const button=$('exportBackup');button.disabled=true;$('message').textContent='';try{const r=await send('exportBackup');if(!r?.ok)throw new Error(r?.error||'无法生成历史备份');const blob=new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Tibo-RESET-历史备份-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('message').textContent='历史备份已导出，可在另一浏览器中导入。';}catch(e){$('message').textContent=e.message;}finally{button.disabled=false;}}
async function importBackup(){const input=$('backupFile'),file=input.files?.[0];if(!file)return;const button=$('importBackup');button.disabled=true;$('message').textContent='';try{const backup=JSON.parse(await file.text()),r=await send('importBackup',{backup});if(!r?.ok)throw new Error(r?.error||'无法导入历史备份');$('message').textContent=`已导入 ${r.imported||0} 条历史记录。`;await refresh();}catch(e){$('message').textContent='导入失败：'+e.message;}finally{input.value='';button.disabled=false;}}
async function reportMissed(){const input=$('missedUrl'),button=$('reportMissed'),url=input.value.trim();const r=await act('feedback',{kind:'missed',url},button);if(r?.ok){input.value='';$('message').textContent='漏报链接已记录，可通过“导出诊断”交给开发者加入回归测试。';}}
async function openMonitorPages(button){if(button)button.disabled=true;$('message').textContent='';try{const r=await send('sourceAll');if(!r?.ok)throw new Error(r?.error||'无法显示监控页面');$('message').textContent='已显示监控窗口；关闭后插件会在下次检查时重新创建。';return r;}catch(e){$('message').textContent=e.message;return null;}finally{if(button)button.disabled=false;}}
async function initOnboarding(){if(!$('onboarding'))return;try{const {publicUi={}}=await chrome.storage.local.get('publicUi');$('onboarding').classList.toggle('hidden',!!publicUi.onboardingDone);}catch{$('onboarding').classList.remove('hidden');}}
async function finishOnboarding(){await chrome.storage.local.set({publicUi:{onboardingDone:true,completedAt:Date.now()}});$('onboarding').classList.add('hidden');$('message').textContent='设置完成，插件会继续自动检查。';}
if($('check'))$('check').onclick=()=>act('check',{},$('check'));if($('source'))$('source').onclick=()=>act('source',{key:'posts'},$('source'));if($('sourceReplies'))$('sourceReplies').onclick=()=>act('source',{key:'replies'},$('sourceReplies'));if($('test'))$('test').onclick=()=>act('test',{},$('test'));
if($('exportDiagnostics'))$('exportDiagnostics').onclick=exportDiagnostics;if($('reportMissed'))$('reportMissed').onclick=reportMissed;
if($('exportBackup'))$('exportBackup').onclick=exportBackup;if($('importBackup'))$('importBackup').onclick=()=>$('backupFile').click();if($('backupFile'))$('backupFile').onchange=importBackup;
if($('openMonitor'))$('openMonitor').onclick=()=>openMonitorPages($('openMonitor'));if($('setupOpen'))$('setupOpen').onclick=()=>openMonitorPages($('setupOpen'));if($('setupTest'))$('setupTest').onclick=()=>act('test',{},$('setupTest'));if($('finishSetup'))$('finishSetup').onclick=finishOnboarding;if($('privacy'))$('privacy').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL('privacy.html')});
$('calendarPrev').onclick=()=>{calendarCursor=moveMonth(calendarCursor,-1);refresh();};$('calendarNext').onclick=()=>{calendarCursor=moveMonth(calendarCursor,1);refresh();};$('calendarToday').onclick=()=>{calendarCursor=monthAt();refresh();};
$('paused').onchange=()=>act('pause',{value:$('paused').checked});$('muted').onchange=()=>act('mute',{value:$('muted').checked});$('ackall').onclick=()=>act('ack',{key:'*'});initOnboarding();refresh();setInterval(refresh,2000);
